Repository rashadalhashmi/EcommerceApp, pull requests merged in 2021-11, with the labels that each got.

#2 add folder (component,service,model)
  src/app/app.component.html
Labels: enhancement

#3 changes
  src/app/app.component.html
Labels: enhancement

#9 ch
  src/app/app.component.html
Labels: enhancement

#22 add font-awesome
  angular.json
  package-lock.json
  package.json
Labels: enhancement

#21 work on the footer component
  src/app/app.component.html
  src/app/components/footer/footer.component.html
  src/app/components/footer/footer.component.scss
  src/assets/cash-on-delivery.svg
  src/assets/cc-amex.svg
  src/assets/cc-mastercard.svg
  src/assets/cc-visa.svg
  src/styles.scss
Labels: enhancement

#24 finish (add-angular-material-feature)
  angular.json
  package-lock.json
  package.json
  src/angular-material/angular-material.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/users/user-auth.module.ts
  src/index.html
  src/styles.scss
Labels: enhancement

#26 Login Form
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/home/home.component.scss
  src/app/components/home/home.component.spec.ts
  src/app/components/home/home.component.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.ts
  src/app/components/users/login/login.component.html
  src/app/components/users/login/login.component.scss
  src/app/components/users/login/login.component.ts
  src/app/components/users/user-auth.module.ts
  src/app/security/user-auth.guard.spec.ts
  src/app/security/user-auth.guard.ts
  src/app/services/user-auth.service.spec.ts
  src/app/services/user-auth.service.ts
  src/app/viewmodel/iuser.ts
  src/environments/environment.ts
Labels: bug

#27 Development
  src/angular-material/angular-material.module.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/navbar/navbar.component.html
  src/app/components/navbar/navbar.component.scss
  src/app/components/users/login-register-view/login-register-view.component.html
  src/app/components/users/login-register-view/login-register-view.component.scss
  src/app/components/users/login-register-view/login-register-view.component.spec.ts
  src/app/components/users/login-register-view/login-register-view.component.ts
  src/app/components/users/login/login.component.html
  src/app/components/users/login/login.component.scss
  src/app/components/users/register/register.component.html
  src/app/components/users/register/register.component.scss
  src/app/components/users/register/register.component.ts
  src/app/components/users/user-auth.module.ts
Labels: bug, enhancement, help wanted
